SET @HOUR= -1;
SELECT (@HOUR := @HOUR+1) AS HOUR, (SELECT COUNT(*) 
                            FROM ANIMAL_OUTS AS OUTS
                            WHERE HOUR(OUTS.DATETIME) = @HOUR) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23